sudo: false

language: node_js

cache:
    directories:
        - node_modules

node:
    - v10.9.0

before_script:
    - npm install

script:
    - npm run test

after_script: npm run coverage

after_success:
    - bash <(curl -s https://codecov.io/bash)
