sudo: required

language: node_js

cache:
    directories:
        - node_modules

node:
    - v10.9.0

before_script:
    - npm config set registry https://registry.npm.taobao.org
    - npm install

script:
    - npm run test && npm run coverage

after_success:
    - bash <(curl -s https://codecov.io/bash)
