
FROM node:latest as builder
COPY package*.json /react-delicacies/
WORKDIR /react-delicacies
RUN npm install --registry=https://registry.npm.taobao.org
COPY . /react-delicacies
RUN npm run build

FROM nginx:latest
COPY nginx.conf /etc/nginx
COPY --from=builder /react-delicacies/dist  /usr/share/nginx/html
