/*
 * @Author: 廉恒凯
 * @Date: 2020-04-27 21:15:15
 * @LastEditors: 廉恒凯
 * @LastEditTime: 2020-05-06 13:19:52
 * @Description: file content
 */
const FETCH_COUNTERLIST_LOADING = 'FETCH_COUNTERLIST_LOADING';

const FETCH_COUNTERLIST_FAILURE = 'FETCH_COUNTERLIST_FAILURE';

const FETCH_COUNTERLIST_SUCCESS = 'FETCH_COUNTERLIST_SUCCESS';

const INCREMENT = 'INCREMENT';

const DECREMENT = 'DECREMENT';

export {
    DECREMENT,
    INCREMENT,
    FETCH_COUNTERLIST_LOADING,
    FETCH_COUNTERLIST_FAILURE,
    FETCH_COUNTERLIST_SUCCESS,
};
